# Generated by Django 6.0.2 on 2026-02-07 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0002_rename_tareas_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='task_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='appweb.listatareas'),
        ),
    ]
